// Generated by gencpp from file turtlesim/GetCameraImage.msg
// DO NOT EDIT!


#ifndef TURTLESIM_MESSAGE_GETCAMERAIMAGE_H
#define TURTLESIM_MESSAGE_GETCAMERAIMAGE_H

#include <ros/service_traits.h>


#include <turtlesim/GetCameraImageRequest.h>
#include <turtlesim/GetCameraImageResponse.h>


namespace turtlesim
{

struct GetCameraImage
{

typedef GetCameraImageRequest Request;
typedef GetCameraImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCameraImage
} // namespace turtlesim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim::GetCameraImage > {
  static const char* value()
  {
    return "a8626d9b6b0964d1462185bf70bbc823";
  }

  static const char* value(const ::turtlesim::GetCameraImage&) { return value(); }
};

template<>
struct DataType< ::turtlesim::GetCameraImage > {
  static const char* value()
  {
    return "turtlesim/GetCameraImage";
  }

  static const char* value(const ::turtlesim::GetCameraImage&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim::GetCameraImageRequest> should match
// service_traits::MD5Sum< ::turtlesim::GetCameraImage >
template<>
struct MD5Sum< ::turtlesim::GetCameraImageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::GetCameraImage >::value();
  }
  static const char* value(const ::turtlesim::GetCameraImageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::GetCameraImageRequest> should match
// service_traits::DataType< ::turtlesim::GetCameraImage >
template<>
struct DataType< ::turtlesim::GetCameraImageRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim::GetCameraImage >::value();
  }
  static const char* value(const ::turtlesim::GetCameraImageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim::GetCameraImageResponse> should match
// service_traits::MD5Sum< ::turtlesim::GetCameraImage >
template<>
struct MD5Sum< ::turtlesim::GetCameraImageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::GetCameraImage >::value();
  }
  static const char* value(const ::turtlesim::GetCameraImageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::GetCameraImageResponse> should match
// service_traits::DataType< ::turtlesim::GetCameraImage >
template<>
struct DataType< ::turtlesim::GetCameraImageResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim::GetCameraImage >::value();
  }
  static const char* value(const ::turtlesim::GetCameraImageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM_MESSAGE_GETCAMERAIMAGE_H
