// Generated by gencpp from file turtlesim/GetFrameSize.msg
// DO NOT EDIT!


#ifndef TURTLESIM_MESSAGE_GETFRAMESIZE_H
#define TURTLESIM_MESSAGE_GETFRAMESIZE_H

#include <ros/service_traits.h>


#include <turtlesim/GetFrameSizeRequest.h>
#include <turtlesim/GetFrameSizeResponse.h>


namespace turtlesim
{

struct GetFrameSize
{

typedef GetFrameSizeRequest Request;
typedef GetFrameSizeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFrameSize
} // namespace turtlesim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim::GetFrameSize > {
  static const char* value()
  {
    return "ed3043f094c99bdd8118bc5b0ddb14ba";
  }

  static const char* value(const ::turtlesim::GetFrameSize&) { return value(); }
};

template<>
struct DataType< ::turtlesim::GetFrameSize > {
  static const char* value()
  {
    return "turtlesim/GetFrameSize";
  }

  static const char* value(const ::turtlesim::GetFrameSize&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim::GetFrameSizeRequest> should match
// service_traits::MD5Sum< ::turtlesim::GetFrameSize >
template<>
struct MD5Sum< ::turtlesim::GetFrameSizeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::GetFrameSize >::value();
  }
  static const char* value(const ::turtlesim::GetFrameSizeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::GetFrameSizeRequest> should match
// service_traits::DataType< ::turtlesim::GetFrameSize >
template<>
struct DataType< ::turtlesim::GetFrameSizeRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim::GetFrameSize >::value();
  }
  static const char* value(const ::turtlesim::GetFrameSizeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim::GetFrameSizeResponse> should match
// service_traits::MD5Sum< ::turtlesim::GetFrameSize >
template<>
struct MD5Sum< ::turtlesim::GetFrameSizeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::GetFrameSize >::value();
  }
  static const char* value(const ::turtlesim::GetFrameSizeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::GetFrameSizeResponse> should match
// service_traits::DataType< ::turtlesim::GetFrameSize >
template<>
struct DataType< ::turtlesim::GetFrameSizeResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim::GetFrameSize >::value();
  }
  static const char* value(const ::turtlesim::GetFrameSizeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM_MESSAGE_GETFRAMESIZE_H
