// Generated by gencpp from file turtlesim/GetFrameSizeResponse.msg
// DO NOT EDIT!


#ifndef TURTLESIM_MESSAGE_GETFRAMESIZERESPONSE_H
#define TURTLESIM_MESSAGE_GETFRAMESIZERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlesim
{
template <class ContainerAllocator>
struct GetFrameSizeResponse_
{
  typedef GetFrameSizeResponse_<ContainerAllocator> Type;

  GetFrameSizeResponse_()
    : width(0.0)
    , height(0.0)  {
    }
  GetFrameSizeResponse_(const ContainerAllocator& _alloc)
    : width(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef float _width_type;
  _width_type width;

   typedef float _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::turtlesim::GetFrameSizeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlesim::GetFrameSizeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetFrameSizeResponse_

typedef ::turtlesim::GetFrameSizeResponse_<std::allocator<void> > GetFrameSizeResponse;

typedef boost::shared_ptr< ::turtlesim::GetFrameSizeResponse > GetFrameSizeResponsePtr;
typedef boost::shared_ptr< ::turtlesim::GetFrameSizeResponse const> GetFrameSizeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlesim::GetFrameSizeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlesim::GetFrameSizeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlesim::GetFrameSizeResponse_<ContainerAllocator1> & lhs, const ::turtlesim::GetFrameSizeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.width == rhs.width &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlesim::GetFrameSizeResponse_<ContainerAllocator1> & lhs, const ::turtlesim::GetFrameSizeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlesim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim::GetFrameSizeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim::GetFrameSizeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim::GetFrameSizeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim::GetFrameSizeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim::GetFrameSizeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim::GetFrameSizeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlesim::GetFrameSizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed3043f094c99bdd8118bc5b0ddb14ba";
  }

  static const char* value(const ::turtlesim::GetFrameSizeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed3043f094c99bddULL;
  static const uint64_t static_value2 = 0x8118bc5b0ddb14baULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlesim::GetFrameSizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlesim/GetFrameSizeResponse";
  }

  static const char* value(const ::turtlesim::GetFrameSizeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlesim::GetFrameSizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 width\n"
"float32 height\n"
"\n"
;
  }

  static const char* value(const ::turtlesim::GetFrameSizeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlesim::GetFrameSizeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFrameSizeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlesim::GetFrameSizeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlesim::GetFrameSizeResponse_<ContainerAllocator>& v)
  {
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLESIM_MESSAGE_GETFRAMESIZERESPONSE_H
