// Generated by gencpp from file turtlesim/GetSonarResponse.msg
// DO NOT EDIT!


#ifndef TURTLESIM_MESSAGE_GETSONARRESPONSE_H
#define TURTLESIM_MESSAGE_GETSONARRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlesim
{
template <class ContainerAllocator>
struct GetSonarResponse_
{
  typedef GetSonarResponse_<ContainerAllocator> Type;

  GetSonarResponse_()
    : closest(0.0)  {
    }
  GetSonarResponse_(const ContainerAllocator& _alloc)
    : closest(0.0)  {
  (void)_alloc;
    }



   typedef float _closest_type;
  _closest_type closest;





  typedef boost::shared_ptr< ::turtlesim::GetSonarResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlesim::GetSonarResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetSonarResponse_

typedef ::turtlesim::GetSonarResponse_<std::allocator<void> > GetSonarResponse;

typedef boost::shared_ptr< ::turtlesim::GetSonarResponse > GetSonarResponsePtr;
typedef boost::shared_ptr< ::turtlesim::GetSonarResponse const> GetSonarResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlesim::GetSonarResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlesim::GetSonarResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlesim::GetSonarResponse_<ContainerAllocator1> & lhs, const ::turtlesim::GetSonarResponse_<ContainerAllocator2> & rhs)
{
  return lhs.closest == rhs.closest;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlesim::GetSonarResponse_<ContainerAllocator1> & lhs, const ::turtlesim::GetSonarResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlesim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim::GetSonarResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim::GetSonarResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim::GetSonarResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim::GetSonarResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim::GetSonarResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim::GetSonarResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlesim::GetSonarResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17b66a616facd3a4f2b8c2dac4757c63";
  }

  static const char* value(const ::turtlesim::GetSonarResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17b66a616facd3a4ULL;
  static const uint64_t static_value2 = 0xf2b8c2dac4757c63ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlesim::GetSonarResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlesim/GetSonarResponse";
  }

  static const char* value(const ::turtlesim::GetSonarResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlesim::GetSonarResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 closest\n"
"\n"
;
  }

  static const char* value(const ::turtlesim::GetSonarResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlesim::GetSonarResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.closest);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetSonarResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlesim::GetSonarResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlesim::GetSonarResponse_<ContainerAllocator>& v)
  {
    s << indent << "closest: ";
    Printer<float>::stream(s, indent + "  ", v.closest);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLESIM_MESSAGE_GETSONARRESPONSE_H
