// Generated by gencpp from file turtlesim/GetSonar.msg
// DO NOT EDIT!


#ifndef TURTLESIM_MESSAGE_GETSONAR_H
#define TURTLESIM_MESSAGE_GETSONAR_H

#include <ros/service_traits.h>


#include <turtlesim/GetSonarRequest.h>
#include <turtlesim/GetSonarResponse.h>


namespace turtlesim
{

struct GetSonar
{

typedef GetSonarRequest Request;
typedef GetSonarResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSonar
} // namespace turtlesim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim::GetSonar > {
  static const char* value()
  {
    return "1cfc3e38ad4d4d3e12abc0a04d9a93e2";
  }

  static const char* value(const ::turtlesim::GetSonar&) { return value(); }
};

template<>
struct DataType< ::turtlesim::GetSonar > {
  static const char* value()
  {
    return "turtlesim/GetSonar";
  }

  static const char* value(const ::turtlesim::GetSonar&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim::GetSonarRequest> should match
// service_traits::MD5Sum< ::turtlesim::GetSonar >
template<>
struct MD5Sum< ::turtlesim::GetSonarRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::GetSonar >::value();
  }
  static const char* value(const ::turtlesim::GetSonarRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::GetSonarRequest> should match
// service_traits::DataType< ::turtlesim::GetSonar >
template<>
struct DataType< ::turtlesim::GetSonarRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim::GetSonar >::value();
  }
  static const char* value(const ::turtlesim::GetSonarRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim::GetSonarResponse> should match
// service_traits::MD5Sum< ::turtlesim::GetSonar >
template<>
struct MD5Sum< ::turtlesim::GetSonarResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::GetSonar >::value();
  }
  static const char* value(const ::turtlesim::GetSonarResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::GetSonarResponse> should match
// service_traits::DataType< ::turtlesim::GetSonar >
template<>
struct DataType< ::turtlesim::GetSonarResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim::GetSonar >::value();
  }
  static const char* value(const ::turtlesim::GetSonarResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM_MESSAGE_GETSONAR_H
