// Generated by gencpp from file turtlesim/GetTurtles.msg
// DO NOT EDIT!


#ifndef TURTLESIM_MESSAGE_GETTURTLES_H
#define TURTLESIM_MESSAGE_GETTURTLES_H

#include <ros/service_traits.h>


#include <turtlesim/GetTurtlesRequest.h>
#include <turtlesim/GetTurtlesResponse.h>


namespace turtlesim
{

struct GetTurtles
{

typedef GetTurtlesRequest Request;
typedef GetTurtlesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTurtles
} // namespace turtlesim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim::GetTurtles > {
  static const char* value()
  {
    return "8e09fa9aad51508cfdcab3b64f048ce0";
  }

  static const char* value(const ::turtlesim::GetTurtles&) { return value(); }
};

template<>
struct DataType< ::turtlesim::GetTurtles > {
  static const char* value()
  {
    return "turtlesim/GetTurtles";
  }

  static const char* value(const ::turtlesim::GetTurtles&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim::GetTurtlesRequest> should match
// service_traits::MD5Sum< ::turtlesim::GetTurtles >
template<>
struct MD5Sum< ::turtlesim::GetTurtlesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::GetTurtles >::value();
  }
  static const char* value(const ::turtlesim::GetTurtlesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::GetTurtlesRequest> should match
// service_traits::DataType< ::turtlesim::GetTurtles >
template<>
struct DataType< ::turtlesim::GetTurtlesRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim::GetTurtles >::value();
  }
  static const char* value(const ::turtlesim::GetTurtlesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim::GetTurtlesResponse> should match
// service_traits::MD5Sum< ::turtlesim::GetTurtles >
template<>
struct MD5Sum< ::turtlesim::GetTurtlesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::GetTurtles >::value();
  }
  static const char* value(const ::turtlesim::GetTurtlesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::GetTurtlesResponse> should match
// service_traits::DataType< ::turtlesim::GetTurtles >
template<>
struct DataType< ::turtlesim::GetTurtlesResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim::GetTurtles >::value();
  }
  static const char* value(const ::turtlesim::GetTurtlesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM_MESSAGE_GETTURTLES_H
