(cl:defpackage package_303770-msg
  (:use )
  (:export
   "<POSE_ACTIONACTION>"
   "POSE_ACTIONACTION"
   "<POSE_ACTIONACTIONFEEDBACK>"
   "POSE_ACTIONACTIONFEEDBACK"
   "<POSE_ACTIONACTIONGOAL>"
   "POSE_ACTIONACTIONGOAL"
   "<POSE_ACTIONACTIONRESULT>"
   "POSE_ACTIONACTIONRESULT"
   "<POSE_ACTIONFEEDBACK>"
   "POSE_ACTIONFEEDBACK"
   "<POSE_ACTIONGOAL>"
   "POSE_ACTIONGOAL"
   "<POSE_ACTIONRESULT>"
   "POSE_ACTIONRESULT"
  ))

