; Auto-generated. Do not edit!


(cl:in-package package_303770-msg)


;//! \htmlinclude pose_actionActionGoal.msg.html

(cl:defclass <pose_actionActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type package_303770-msg:pose_actionGoal
    :initform (cl:make-instance 'package_303770-msg:pose_actionGoal)))
)

(cl:defclass pose_actionActionGoal (<pose_actionActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <pose_actionActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'pose_actionActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name package_303770-msg:<pose_actionActionGoal> is deprecated: use package_303770-msg:pose_actionActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <pose_actionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader package_303770-msg:header-val is deprecated.  Use package_303770-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <pose_actionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader package_303770-msg:goal_id-val is deprecated.  Use package_303770-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <pose_actionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader package_303770-msg:goal-val is deprecated.  Use package_303770-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <pose_actionActionGoal>) ostream)
  "Serializes a message object of type '<pose_actionActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <pose_actionActionGoal>) istream)
  "Deserializes a message object of type '<pose_actionActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<pose_actionActionGoal>)))
  "Returns string type for a message object of type '<pose_actionActionGoal>"
  "package_303770/pose_actionActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'pose_actionActionGoal)))
  "Returns string type for a message object of type 'pose_actionActionGoal"
  "package_303770/pose_actionActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<pose_actionActionGoal>)))
  "Returns md5sum for a message object of type '<pose_actionActionGoal>"
  "a0bdbbb3bfdac1eb4a50ba792052760a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'pose_actionActionGoal)))
  "Returns md5sum for a message object of type 'pose_actionActionGoal"
  "a0bdbbb3bfdac1eb4a50ba792052760a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<pose_actionActionGoal>)))
  "Returns full string definition for message of type '<pose_actionActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%pose_actionGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: package_303770/pose_actionGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'pose_actionActionGoal)))
  "Returns full string definition for message of type 'pose_actionActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%pose_actionGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: package_303770/pose_actionGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <pose_actionActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <pose_actionActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'pose_actionActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
