// Generated by gencpp from file package_303770/pose_actionResult.msg
// DO NOT EDIT!


#ifndef PACKAGE_303770_MESSAGE_POSE_ACTIONRESULT_H
#define PACKAGE_303770_MESSAGE_POSE_ACTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package_303770
{
template <class ContainerAllocator>
struct pose_actionResult_
{
  typedef pose_actionResult_<ContainerAllocator> Type;

  pose_actionResult_()
    : status()  {
    }
  pose_actionResult_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::package_303770::pose_actionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package_303770::pose_actionResult_<ContainerAllocator> const> ConstPtr;

}; // struct pose_actionResult_

typedef ::package_303770::pose_actionResult_<std::allocator<void> > pose_actionResult;

typedef boost::shared_ptr< ::package_303770::pose_actionResult > pose_actionResultPtr;
typedef boost::shared_ptr< ::package_303770::pose_actionResult const> pose_actionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package_303770::pose_actionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package_303770::pose_actionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::package_303770::pose_actionResult_<ContainerAllocator1> & lhs, const ::package_303770::pose_actionResult_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::package_303770::pose_actionResult_<ContainerAllocator1> & lhs, const ::package_303770::pose_actionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace package_303770

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::package_303770::pose_actionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package_303770::pose_actionResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package_303770::pose_actionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package_303770::pose_actionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_303770::pose_actionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_303770::pose_actionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package_303770::pose_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fe5af303955c287688e7347e9b00278";
  }

  static const char* value(const ::package_303770::pose_actionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fe5af303955c287ULL;
  static const uint64_t static_value2 = 0x688e7347e9b00278ULL;
};

template<class ContainerAllocator>
struct DataType< ::package_303770::pose_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package_303770/pose_actionResult";
  }

  static const char* value(const ::package_303770::pose_actionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package_303770::pose_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result\n"
"string status\n"
;
  }

  static const char* value(const ::package_303770::pose_actionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package_303770::pose_actionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_actionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package_303770::pose_actionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package_303770::pose_actionResult_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE_303770_MESSAGE_POSE_ACTIONRESULT_H
