// Generated by gencpp from file package_303770/pose_actionGoal.msg
// DO NOT EDIT!


#ifndef PACKAGE_303770_MESSAGE_POSE_ACTIONGOAL_H
#define PACKAGE_303770_MESSAGE_POSE_ACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package_303770
{
template <class ContainerAllocator>
struct pose_actionGoal_
{
  typedef pose_actionGoal_<ContainerAllocator> Type;

  pose_actionGoal_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  pose_actionGoal_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::package_303770::pose_actionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package_303770::pose_actionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct pose_actionGoal_

typedef ::package_303770::pose_actionGoal_<std::allocator<void> > pose_actionGoal;

typedef boost::shared_ptr< ::package_303770::pose_actionGoal > pose_actionGoalPtr;
typedef boost::shared_ptr< ::package_303770::pose_actionGoal const> pose_actionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package_303770::pose_actionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package_303770::pose_actionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::package_303770::pose_actionGoal_<ContainerAllocator1> & lhs, const ::package_303770::pose_actionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::package_303770::pose_actionGoal_<ContainerAllocator1> & lhs, const ::package_303770::pose_actionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace package_303770

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::package_303770::pose_actionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package_303770::pose_actionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package_303770::pose_actionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package_303770::pose_actionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_303770::pose_actionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_303770::pose_actionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package_303770::pose_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::package_303770::pose_actionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::package_303770::pose_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package_303770/pose_actionGoal";
  }

  static const char* value(const ::package_303770::pose_actionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package_303770::pose_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::package_303770::pose_actionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package_303770::pose_actionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_actionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package_303770::pose_actionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package_303770::pose_actionGoal_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE_303770_MESSAGE_POSE_ACTIONGOAL_H
