// Generated by gencpp from file package_303770/pose_actionFeedback.msg
// DO NOT EDIT!


#ifndef PACKAGE_303770_MESSAGE_POSE_ACTIONFEEDBACK_H
#define PACKAGE_303770_MESSAGE_POSE_ACTIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package_303770
{
template <class ContainerAllocator>
struct pose_actionFeedback_
{
  typedef pose_actionFeedback_<ContainerAllocator> Type;

  pose_actionFeedback_()
    : a(0.0)
    , b(0.0)
    , c(0.0)  {
    }
  pose_actionFeedback_(const ContainerAllocator& _alloc)
    : a(0.0)
    , b(0.0)
    , c(0.0)  {
  (void)_alloc;
    }



   typedef double _a_type;
  _a_type a;

   typedef double _b_type;
  _b_type b;

   typedef double _c_type;
  _c_type c;





  typedef boost::shared_ptr< ::package_303770::pose_actionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package_303770::pose_actionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct pose_actionFeedback_

typedef ::package_303770::pose_actionFeedback_<std::allocator<void> > pose_actionFeedback;

typedef boost::shared_ptr< ::package_303770::pose_actionFeedback > pose_actionFeedbackPtr;
typedef boost::shared_ptr< ::package_303770::pose_actionFeedback const> pose_actionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package_303770::pose_actionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package_303770::pose_actionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::package_303770::pose_actionFeedback_<ContainerAllocator1> & lhs, const ::package_303770::pose_actionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b &&
    lhs.c == rhs.c;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::package_303770::pose_actionFeedback_<ContainerAllocator1> & lhs, const ::package_303770::pose_actionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace package_303770

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::package_303770::pose_actionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package_303770::pose_actionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package_303770::pose_actionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package_303770::pose_actionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_303770::pose_actionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_303770::pose_actionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package_303770::pose_actionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ffac936c9b4e668039d250d853dc9b2";
  }

  static const char* value(const ::package_303770::pose_actionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ffac936c9b4e668ULL;
  static const uint64_t static_value2 = 0x039d250d853dc9b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::package_303770::pose_actionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package_303770/pose_actionFeedback";
  }

  static const char* value(const ::package_303770::pose_actionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package_303770::pose_actionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float64 a\n"
"float64 b\n"
"float64 c\n"
;
  }

  static const char* value(const ::package_303770::pose_actionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package_303770::pose_actionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_actionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package_303770::pose_actionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package_303770::pose_actionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<double>::stream(s, indent + "  ", v.c);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE_303770_MESSAGE_POSE_ACTIONFEEDBACK_H
